=== JMRI/jmri-test/xml/schema/appearancetable.xsd
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>

<!-- XML Schema for JMRI aspect-signaling support.                          -->

<!-- $Id: appearancetable.xsd,v 1.10 2010-01-03 22:05:54 jacobsen Exp $ -->

<!-- This schema is part of JMRI. Copyright 2009.                           -->
<!--                                                                        -->
<!-- JMRI is free software; you can redistribute it and/or modify it under  -->
<!-- the terms of version 2 of the GNU General Public License as published  -->
<!-- by the Free Software Foundation. See the "COPYING" file for a copy     -->
<!-- of this license.                                                       -->
<!--                                                                        -->
<!-- JMRI is distributed in the hope that it will be useful, but WITHOUT    -->
<!-- ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or  -->
<!-- FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License  -->
<!-- for more details.                                                      -->

<xs:schema xmlns:xs  ="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:docbook="http://docbook.org/ns/docbook"
           xmlns:jmri="http://jmri.org/xml/schema/JMRIschema"
           xsi:schemaLocation="
                http://jmri.org/xml/schema/JMRIschema http://jmri.org/xml/schema/JMRIschema.xsd
                http://docbook.org/ns/docbook http://jmri.org/xml/schema/DocBook.xsd
            "
           >

<xs:import namespace='http://docbook.org/ns/docbook' schemaLocation='DocBook.xsd'/>

  <xs:element name="appearancetable">
    <xs:annotation>
        <xs:appinfo>
            <jmri:class>jmri.implementation.DefaultSignalAppearanceMap</jmri:class>
            <jmri:class>jmri.jmrit.beantable.signalmast.AddSignalMastPanel</jmri:class>
        </xs:appinfo>
        <xs:documentation>
        We allow unlimited extension at the end of the appearancetable element
        for the purposes of automatically-created documentation, 
        but only the aspecttable, name and appearances elements are used by the
        program.
        </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        
        <xs:element ref="docbook:authorgroup" minOccurs="1" maxOccurs="unbounded" >
          <xs:annotation><xs:documentation>
          DocBook element(s) describing the authors in standard form
          </xs:documentation></xs:annotation>
        </xs:element>
        
        <xs:element ref="docbook:revhistory" minOccurs="1" maxOccurs="unbounded" >
          <xs:annotation><xs:documentation>
          DocBook element(s) describing the revision history in standard form
          </xs:documentation></xs:annotation>
        </xs:element>

        <xs:element name="aspecttable" minOccurs="1" maxOccurs="1">
          <xs:annotation><xs:documentation>
          Content of this element must match the name of an
          aspect table, as it's used to retrieve a 
          SignalSystem at run time.
          </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="name" minOccurs="1" maxOccurs="1" >
          <xs:annotation><xs:documentation>
          Content of this element defines the name that's present to the
          user when selecting an appearance table to use.
          </xs:documentation></xs:annotation>
        </xs:element>

        <xs:element name="reference" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="description" minOccurs="0" maxOccurs="unbounded" />

        <xs:element name="appearances" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              
              <xs:element name="appearance" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:annotation><xs:documentation>
                  We allow unlimited extension at the end of the aspect element
                  for the purposes of automatically-created documentation, 
                  but only the aspectname and show element(s) are used by the
                  program.
                  </xs:documentation></xs:annotation>
                  <xs:sequence>
                    
                    <xs:element name="aspectname" minOccurs="1" maxOccurs="1" >
                      <xs:annotation><xs:documentation>
                      This must match the "name" element of exactly one
                      "aspect" element in the "aspects.xml" file.
                      </xs:documentation></xs:annotation>
                    </xs:element>
                    <xs:element name="show" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element name="reference" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element name="imagelink" minOccurs="0" maxOccurs="unbounded" />
                    
                    <!-- next line causes a "Unique Particle Attribution" error -->
                    <!-- <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/> -->

                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JMRI/jmri-test/xml/signals/BR-2003/appearance-4-i-c.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="http://jmri.org/xml/XSLT/appearancetable.xsl" type="text/xsl"?>

<appearancetable
    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation = "http://jmri.org/xml/schema/appearancetable.xsd"
>

  <copyright xmlns="http://docbook.org/ns/docbook">
    <year>2010</year><holder>JMRI</holder>
  </copyright>
  
  <authorgroup xmlns="http://docbook.org/ns/docbook">
    <author>
        <personname><firstname>Kevin</firstname><surname>Dickerson</surname></personname>

    </author>    
  </authorgroup>

  <revhistory xmlns="http://docbook.org/ns/docbook">
    <revision>
        <revnumber>1</revnumber>
        <date>2010-01-18</date>
        <authorinitials>KD</authorinitials>
        <revremark>Initial Version</revremark>
    </revision>    
  </revhistory>
  
  <aspecttable>BR</aspecttable>

  <name>4 Aspect Signal Head + Call On(individual aspects)</name>
  <reference></reference>
  <description>This uses 4 single state signal heads to represent the main signal and a further signal head to represent the Call-on</description>

  <name>Sample of full file format</name>
  <reference></reference>
  <description></description>
  
  <appearances>

    <appearance>
      <aspectname>Proceed</aspectname>
      <show>dark</show>
      <show>green</show>
      <show>dark</show>
      <show>dark</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4Proceed(wc).gif</imagelink>
    </appearance>

    <appearance>
      <aspectname>Caution</aspectname>
      <show>dark</show>
      <show>dark</show>
      <show>yellow</show>
      <show>dark</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4Caution(wc).gif</imagelink>
    </appearance>
    
    <appearance>
      <aspectname>Flash Caution</aspectname>
      <show>dark</show>
      <show>dark</show>
      <show>flashyellow</show>
      <show>dark</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4FlashCaution(wc).gif</imagelink>
    </appearance>
    
    <appearance>
      <aspectname>Preliminary Caution</aspectname>
      <show>yellow</show>
      <show>dark</show>
      <show>yellow</show>
      <show>dark</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4PriCaution(wc).gif</imagelink>
    </appearance>
    
    <appearance>
      <aspectname>Flash Preliminary Caution</aspectname>
      <show>flashyellow</show>
      <show>dark</show>
      <show>flashyellow</show>
      <show>dark</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4FlashPriCaution(wc).gif</imagelink>
    </appearance>
    
    <appearance>
      <aspectname>Danger</aspectname>
      <show>dark</show>
      <show>dark</show>
      <show>dark</show>
      <show>red</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4Danger(wc).gif</imagelink>
    </appearance>
    
    <appearance>
      <aspectname>Position Light Proceed at Caution (White/White)</aspectname>
      <show>dark</show>
      <show>dark</show>
      <show>dark</show>
      <show>red</show>
      <show>lunar</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4DangerCallOn.gif</imagelink>
    </appearance>

  </appearances>
</appearancetable>

=== JMRI/jmri-test/xml/signals/BR-2003/appearance-4-i.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="http://jmri.org/xml/XSLT/appearancetable.xsl" type="text/xsl"?>

<appearancetable
    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation = "http://jmri.org/xml/schema/appearancetable.xsd"
>

  <copyright xmlns="http://docbook.org/ns/docbook">
    <year>2010</year><holder>JMRI</holder>
  </copyright>
  
  <authorgroup xmlns="http://docbook.org/ns/docbook">
    <author>
        <personname><firstname>Kevin</firstname><surname>Dickerson</surname></personname>

    </author>    
  </authorgroup>

  <revhistory xmlns="http://docbook.org/ns/docbook">
    <revision>
        <revnumber>1</revnumber>
        <date>2010-01-18</date>
        <authorinitials>KD</authorinitials>
        <revremark>Initial Version</revremark>
    </revision>    
  </revhistory>
  
  <aspecttable>BR</aspecttable>

  <name>4 Aspect Signal Head (individual aspects)</name>
  <reference></reference>
  <description>This uses 4 single state signal heads to represent the main signal</description>

  <name>Sample of full file format</name>
  <reference></reference>
  <description></description>
  
  <appearances>

    <appearance>
      <aspectname>Proceed</aspectname>
      <show>dark</show>
      <show>green</show>
      <show>dark</show>
      <show>dark</show>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4Proceed.gif</imagelink>
      <reference></reference>
    </appearance>

    <appearance>
      <aspectname>Caution</aspectname>
      <show>dark</show>
      <show>dark</show>
      <show>yellow</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4Caution.gif</imagelink>
    </appearance>
    
    <appearance>
      <aspectname>Flash Caution</aspectname>
      <show>dark</show>
      <show>dark</show>
      <show>flashyellow</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4FlashCaution.gif</imagelink>
    </appearance>
    
    <appearance>
      <aspectname>Preliminary Caution</aspectname>
      <show>yellow</show>
      <show>dark</show>
      <show>yellow</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4PriCaution.gif</imagelink>
    </appearance>
    
    <appearance>
      <aspectname>Flash Preliminary Caution</aspectname>
      <show>flashyellow</show>
      <show>dark</show>
      <show>flashyellow</show>
      <show>dark</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4FlashPriCaution.gif</imagelink>
    </appearance>
    
    <appearance>
      <aspectname>Danger</aspectname>
      <show>dark</show>
      <show>dark</show>
      <show>dark</show>
      <show>red</show>
      <reference></reference>
      <imagelink>../../../resources/icons/BritishRailSignals/cls4Danger.gif</imagelink>
    </appearance>
    
  </appearances>
</appearancetable>
