=== JMRI/jmri-test/xml/schema/aspecttable.xsd
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>

<!-- Test schema for JMRI aspect-signaling support                          -->

<!-- This is an experimental organization,                                  -->
<!-- and will certainly be changed in the near future                       -->

<!-- $Id: aspecttable.xsd,v 1.5 2009-12-30 19:39:13 jacobsen Exp $ -->

<!-- This schema is part of JMRI. Copyright 2009.                           -->
<!--                                                                        -->
<!-- JMRI is free software; you can redistribute it and/or modify it under  -->
<!-- the terms of version 2 of the GNU General Public License as published  -->
<!-- by the Free Software Foundation. See the "COPYING" file for a copy     -->
<!-- of this license.                                                       -->
<!--                                                                        -->
<!-- JMRI is distributed in the hope that it will be useful, but WITHOUT    -->
<!-- ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or  -->
<!-- FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License  -->
<!-- for more details.                                                      -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:jmri="http://jmri.org/xml/schema/JMRIschema"
           xsi:schemaLocation="http://jmri.org/xml/schema/JMRIschema http://jmri.org/xml/schema/JMRIschema.xsd"
           >
  <xs:element name="aspecttable">
    <xs:annotation>
        <xs:documentation>
        ******** Optional items  **********
        The first instance of each of these
        becomes a property of the signal
        system named bean.
        </xs:documentation>
        <xs:appinfo>
            <jmri:class>jmri.managers.DefaultSignalSystemManager</jmri:class>
        </xs:appinfo>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>

        <xs:element name="name" minOccurs="1" maxOccurs="1"></xs:element>

        <xs:element name="date" minOccurs="0" maxOccurs="1"></xs:element>
        <xs:element name="reference" minOccurs="0" maxOccurs="unbounded"></xs:element>
        

        <xs:element name="aspects" minOccurs="1" maxOccurs="1">
        <xs:annotation><xs:documentation>
        ******** Required Aspect Table  **********
        </xs:documentation></xs:annotation>
          <xs:complexType>
            <xs:sequence>
              
              <xs:element name="aspect" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:annotation><xs:documentation>
                  ******** Optional items  **********
                  The first instance of each of these
                  becomes a property of the specific 
                  aspect.
                  </xs:documentation></xs:annotation>
                  
                  <xs:sequence>
                    
                    <xs:element name="name" minOccurs="1" maxOccurs="1"></xs:element>
                    
                    <xs:element name="title" minOccurs="0" maxOccurs="1"></xs:element>
                    <xs:element name="indication" minOccurs="0" maxOccurs="1"></xs:element>
                    <xs:element name="description" minOccurs="0" maxOccurs="unbounded"></xs:element>
                    <xs:element name="reference" minOccurs="0" maxOccurs="unbounded"></xs:element>
                    <xs:element name="comment" minOccurs="0" maxOccurs="unbounded"></xs:element>
                    <xs:element name="imagelink" minOccurs="0" maxOccurs="unbounded"></xs:element>
                    
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
                
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JMRI/jmri-test/xml/signals/SPTCO-1960/aspects.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="aspecttable.xsl" type="text/xsl"?>

<aspecttable
    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation = "http://jmri.org/xml/schema/aspecttable.xsd"
>
  <name>SPTCO-1960</name>
  <date>1960</date>
  <reference>This directory contains signaling definitions corresponding to the 1960 Southern Pacific Transportation Company rules as described in the "Rules and Regulations of the Transportation Department" booklet.</reference>
  <reference>See http://sptco.railspot.com/SP_Rules-and-Regs/Rules-and-Regs_1960.htm</reference>
  <aspects>
    <aspect>
      <title>Rule 281</title>
      <name>Block signal green</name>
      <indication>Proceed</indication>
    </aspect>
    <aspect>
      <title>Rule 282</title>
      <name>Block signal green</name>
      <indication>Proceed except on diverging route</indication>
    </aspect>
    <aspect>
      <title>Rule 283</title>
      <name>Block signal green for diverging route</name>
      <indication>Proceed on diverging route</indication>
    </aspect>
    <aspect>
      <title>Rule 284</title>
      <name>Block signal yellow over green</name>
      <indication>Reduce to medium speed and proceed. Next signal indicates "Proceed on diverging route"</indication>
    </aspect>
    <aspect>
      <title>Rule 285</title>
      <name>Approach signal yellow</name>
      <indication>Proceed not exceeding medium speed, prepared to stop short of next home signal.</indication>
    </aspect>
    <aspect>
      <title>Rule 285-A</title>
      <name>Approach medium - flashing yellow</name>
      <indication>Proceed prepared to pass next signal at not exceeding medium speed.</indication>
    </aspect>
    <aspect>
      <title>Rule 286</title>
      <name>Distant signal yellow</name>
      <indication>Proceed not exceeding medium speed, prepared to stop short of next home signal.</indication>
    </aspect>
    <aspect>
      <title>Rule 287</title>
      <name>Grade signal red</name>
      <indication>Reduce to restricted speed and proceed.</indication>
    </aspect>
    <aspect>
      <title>Rule 288</title>
      <name>Home signal yellow for diverging route</name>
      <indication>Proceed on diverging route at restricted speed.</indication>
    </aspect>
    <aspect>
      <title>Rule 289</title>
      <name>Home signal red over lunar</name>
      <indication>Proceed without stopping at restricted speed on other than main track.</indication>
    </aspect>
    <aspect>
      <title>Rule 290</title>
      <name>Home signal red</name>
      <indication>Stop.</indication>
    </aspect>
    <aspect>
      <title>Rule 291</title>
      <name>Flashing yellow</name>
      <indication>Stop. Then proceed at restricted speed without calling dispatcher or signal operator.</indication>
    </aspect>
    <aspect>
      <title>Rule 292</title>
      <name>Flashing white</name>
      <indication>Stop. When flashing white displayed be governed by special instructions.</indication>
    </aspect>
    <aspect>
      <title>Rule 293</title>
      <name>Home signal red, with triangular plate</name>
      <indication>Stop. Inspect train, track or structure as provided in special instrutions, and proceed through remainder of block in accordance with provisions of Rule 507, 509, 510, 663, 744, or 776, as the case may be.</indication>
    </aspect>
  </aspects>
</aspecttable>
