=== JMRI/jmri-test/xml/schema/decoder.xsd
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>

<!-- Schema for JMRI decoder definitions       -->

<!-- $Id: decoder.xsd,v 1.3 2010-01-26 03:23:34 jacobsen Exp $ -->

<!-- This schema is part of JMRI. Copyright 2009, 2010.                     -->
<!--                                                                        -->
<!-- JMRI is free software; you can redistribute it and/or modify it under  -->
<!-- the terms of version 2 of the GNU General Public License as published  -->
<!-- by the Free Software Foundation. See the "COPYING" file for a copy     -->
<!-- of this license.                                                       -->
<!--                                                                        -->
<!-- JMRI is distributed in the hope that it will be useful, but WITHOUT    -->
<!-- ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or  -->
<!-- FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License  -->
<!-- for more details.                                                      -->


    <!-- need variable -->
    <!-- need ivariable -->
    
    <!-- not yet in proper Venetian blind form -->
    <!-- needs to share the pane type with programmer definition -->
    
    <!-- need documentation, etc -->
    <!-- need attribute restrictions -->
    
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:docbook="http://docbook.org/ns/docbook"
           xmlns:jmri="http://jmri.org/xml/schema/JMRIschema"
           xsi:schemaLocation="
                http://jmri.org/xml/schema/JMRIschema http://jmri.org/xml/schema/JMRIschema.xsd
                http://docbook.org/ns/docbook http://jmri.org/xml/schema/docbook/DocBook.xsd
            "
           >

<xs:annotation>
    <xs:documentation>
      Defines the JMRI decoder definition files.
    </xs:documentation>
    <xs:appinfo>
        <jmri:usingclass configurexml="false">jmri.jmrit.decoderdefn.DecoderFile</jmri:usingclass>
        <jmri:usingclass configurexml="false">jmri.jmrit.symbolicprog.VariableTableModel</jmri:usingclass>
    </xs:appinfo>
</xs:annotation>

  <xs:element name="decoder-config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" type="VersionType" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="decoder" type="DecoderType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="pane"    type="PaneType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="VersionType">
      <xs:attribute name="author" />
      <xs:attribute name="version" />
      <xs:attribute name="lastUpdated" />
  </xs:complexType>

  <xs:complexType name="DecoderType">
    <xs:sequence>

      <xs:element name="family" type="FamilyType" minOccurs="1" maxOccurs="1" />

      <xs:element name="programming" minOccurs="1" maxOccurs="1" >
        <xs:complexType>
          <xs:attribute name="direct" />
          <xs:attribute name="paged" />
          <xs:attribute name="register" />
          <xs:attribute name="ops" />
        </xs:complexType>
      </xs:element>

      <xs:element name="variables" type="VariablesType" minOccurs="1" maxOccurs="1" />

      <xs:element name="resets" type="ResetsType" minOccurs="0" maxOccurs="1"/>

    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="FamilyType">
    <xs:sequence>

      <xs:element name="model" minOccurs="0" maxOccurs="unbounded" />

      <xs:element name="functionlabels" minOccurs="0" maxOccurs="1">
        <xs:complexType><xs:sequence>
          <xs:element name="functionlabel" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="num" type="xs:string"/>
                  <xs:attribute name="lockable" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
          </xs:element>
        </xs:sequence></xs:complexType>
      </xs:element>

    </xs:sequence>
    <xs:attribute name="name" />
    <xs:attribute name="mfg" />
    <xs:attribute name="lowVersionID" />
  </xs:complexType>

  <xs:complexType name="VariablesType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="constant" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="variable" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="ivariable" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ResetsType">
    <xs:sequence>
      <xs:element name="ifactReset" minOccurs="0" maxOccurs="unbounded" >
        <xs:complexType>
          <xs:attribute name="label" type="xs:string"/>
          <xs:attribute name="CVname" type="xs:string"/>
          <xs:attribute name="CV" type="xs:string"/>
          <xs:attribute name="PI" type="xs:string"/>
          <xs:attribute name="SI" type="xs:string"/>
          <xs:attribute name="default" type="xs:string"/>
          <xs:attribute name="item" type="xs:string"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PaneType">
    <xs:choice>
      <xs:element name="row" type="PaneRowType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="column" type="PaneColumnType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="PaneRowType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="column" type="PaneColumnType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="label" type="LabelType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="display" type="DisplayType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="separator" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="indxcvtable" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PaneColumnType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="row" type="PaneRowType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="label" type="LabelType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="display" type="DisplayType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="separator" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="indxcvtable" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LabelType">
    <xs:attribute name="label" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="DisplayType">
    <xs:attribute name="item" type="xs:string"/>
    <xs:attribute name="label" type="xs:string"/>
    <xs:attribute name="format" type="xs:string"/>
    <xs:attribute name="layout" type="xs:string"/>
    <xs:attribute name="tooltip" type="xs:string"/>
  </xs:complexType>


</xs:schema>

=== JMRI/jmri-test/3.7.4/xml/decoders/zimo/PaneRandomSounds.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/decoder.xsl"?>
<!-- version 1 - for Unified Software -->
<pane name="Random Sounds" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://jmri.org/xml/schema/decoder.xsd">
  <column>
    <label label="Random Generator Z1">
      <label>Random Generator Z1</label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Minimum interval for random generator Z1" label="Minimum interval">
      <label>Minimum interval</label>
    </display>
    <display item="Maximum interval for random generator Z1" label="Maximum interval">
      <label>Maximum interval</label>
    </display>
    <display item="Playback length for random generator Z1" label="Playback length">
      <label>Playback length</label>
    </display>
    <label label=" ">
      <label> </label>
    </label>
    <label label=" ">
      <label> </label>
    </label>
    <label label="Random Generator Z2">
      <label>Random Generator Z2</label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Minimum interval for random generator Z2" label="Minimum interval">
      <label>Minimum interval</label>
    </display>
    <display item="Maximum interval for random generator Z2" label="Maximum interval">
      <label>Maximum interval</label>
    </display>
    <display item="Playback length for random generator Z2" label="Playback length">
      <label>Playback length</label>
    </display>
    <label label=" ">
      <label> </label>
    </label>
    <label label=" ">
      <label> </label>
    </label>
    <label label="Random Generator Z3">
      <label>Random Generator Z3</label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Minimum interval for random generator Z3" label="Minimum interval">
      <label>Minimum interval</label>
    </display>
    <display item="Maximum interval for random generator Z3" label="Maximum interval">
      <label>Maximum interval</label>
    </display>
    <display item="Playback length for random generator Z3" label="Playback length">
      <label>Playback length</label>
    </display>
    <label label=" ">
      <label> </label>
    </label>
    <label label=" ">
      <label> </label>
    </label>
    <label label="Random Generator Z4">
      <label>Random Generator Z4</label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Minimum interval for random generator Z4" label="Minimum interval">
      <label>Minimum interval</label>
    </display>
    <display item="Maximum interval for random generator Z4" label="Maximum interval">
      <label>Maximum interval</label>
    </display>
    <display item="Playback length for random generator Z4" label="Playback length">
      <label>Playback length</label>
    </display>
  </column>
  <column>
    <label label="Random Generator Z5">
      <label>Random Generator Z5</label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Minimum interval for random generator Z5" label="Minimum interval">
      <label>Minimum interval</label>
    </display>
    <display item="Maximum interval for random generator Z5" label="Maximum interval">
      <label>Maximum interval</label>
    </display>
    <display item="Playback length for random generator Z5" label="Playback length">
      <label>Playback length</label>
    </display>
    <label label=" ">
      <label> </label>
    </label>
    <label label=" ">
      <label> </label>
    </label>
    <label label="Random Generator Z6">
      <label>Random Generator Z6</label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Minimum interval for random generator Z6" label="Minimum interval">
      <label>Minimum interval</label>
    </display>
    <display item="Maximum interval for random generator Z6" label="Maximum interval">
      <label>Maximum interval</label>
    </display>
    <display item="Playback length for random generator Z6" label="Playback length">
      <label>Playback length</label>
    </display>
    <label label=" ">
      <label> </label>
    </label>
    <label label=" ">
      <label> </label>
    </label>
    <label label="Random Generator Z7">
      <label>Random Generator Z7</label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Minimum interval for random generator Z7" label="Minimum interval">
      <label>Minimum interval</label>
    </display>
    <display item="Maximum interval for random generator Z7" label="Maximum interval">
      <label>Maximum interval</label>
    </display>
    <display item="Playback length for random generator Z7" label="Playback length">
      <label>Playback length</label>
    </display>
    <label label=" ">
      <label> </label>
    </label>
    <label label=" ">
      <label> </label>
    </label>
    <label label="Random Generator Z8">
      <label>Random Generator Z8</label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Minimum interval for random generator Z8" label="Minimum interval">
      <label>Minimum interval</label>
    </display>
    <display item="Maximum interval for random generator Z8" label="Maximum interval">
      <label>Maximum interval</label>
    </display>
    <display item="Playback length for random generator Z8" label="Playback length">
      <label>Playback length</label>
    </display>
  </column>
  <name>Random Sounds</name>
</pane>

=== JMRI/jmri-test/xml/decoders/zimo/PaneSmoke.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/decoder.xsl"?>
<!-- version 1 - for Unified Software -->
<!-- version 1.1 2 Aug 11 JES
                 - made item name for CV 133 more generic
-->
<pane name="Smoke" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://jmri.org/xml/schema/decoder.xsd">
  <column>
    <display item="Smoke Characteristic"/>
    <label label=" ">
      <label> </label>
    </label>
    <row>
      <column>
        <display item="Smoke PWM at standstill"/>
        <display item="Smoke PWM at minimum speed"/>
        <display item="Smoke PWM at max speed"/>
      </column>
      <column>
        <display item="Smoke PWM at standstill" format="hslider" label="">
          <label/>
        </display>
        <display item="Smoke PWM at minimum speed" format="hslider" label="">
          <label/>
        </display>
        <display item="Smoke PWM at max speed" format="hslider" label="">
          <label/>
        </display>
      </column>
    </row>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Automatic Shut-down of Smoke Generator"/>
    <label label=" ">
      <label> </label>
    </label>
    <label label=" ">
      <label> </label>
    </label>
    <label label=" ">
      <label> </label>
    </label>
    <label label="Smoke Fan Settings">
      <label> </label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <display item="Function Output as virtual Cam or Smoke Fan"/>
    <label label=" ">
      <label> </label>
    </label>
    <row>
      <column>
        <display item="Fan Speed at Standstill"/>
      </column>
      <column>
        <display item="Fan Speed at Standstill" format="hslider" label="">
          <label/>
        </display>
      </column>
    </row>
    <label label=" ">
      <label> </label>
    </label>
    <label label=" ">
      <label> </label>
    </label>
    <label label="Settings for Diesels">
      <label> </label>
    </label>
    <separator/>
    <label label=" ">
      <label> </label>
    </label>
    <row>
      <column>
        <display item="Smoke Fan Speed at Steady Speed"/>
        <display item="Smoke Fan Speed at Startup and Acceleration"/>
      </column>
      <column>
        <display item="Smoke Fan Speed at Steady Speed" format="hslider" label="">
          <label/>
        </display>
        <display item="Smoke Fan Speed at Startup and Acceleration" format="hslider" label="">
          <label/>
        </display>
      </column>
    </row>
  </column>
</pane>

=== JMRI/jmri-test/xml/decoders/qsi/PaneBalanceV9.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/decoder.xsl"?>
<!-- Copyright (C) JMRI 2005, 2007 All rights reserved -->
<!--                                                                        -->
<!-- JMRI is free software; you can redistribute it and/or modify it under  -->
<!-- the terms of version 2 of the GNU General Public License as published  -->
<!-- by the Free Software Foundation. See the "COPYING" file for a copy     -->
<!-- of this license.                                                       -->
<!--                                                                        -->
<!-- JMRI is distributed in the hope that it will be useful, but WITHOUT    -->
<!-- ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or  -->
<!-- FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License  -->
<!-- for more details.                                                      -->
<!-- version 1 - new file panes for QSi V8 files -->
<pane name="Component Balance" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://jmri.org/xml/schema/decoder.xsd">
  <column>
    <row>
      <column>
        <label label="JMRI 2.13.2 or later is required for QSI V9"/>
        <label label="When programming in Ops-mode, see note on QSI Misc. tab"/>
        <label label=" "/>
        <display item="CV56.254.6"/>
        <label label=" "/>
      </column>
    </row>
    <row>
      <label label="Select the speaker and percent reduction of sound output for that speaker, other speaker remains at 100%"/>
    </row>
    <row>
      <column>
        <row>
          <column>
            <display item="CV128.10.0 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.10.0 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.10.0 Value" layout="above" label=""/>
              <display item="CV128.10.0 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.10.10 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.10.10 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.10.10 Value" layout="above" label=""/>
              <display item="CV128.10.10 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.10.20 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.10.20 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.10.20 Value" layout="above" label=""/>
              <display item="CV128.10.20 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.10.30 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.10.30 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.10.30 Value" layout="above" label=""/>
              <display item="CV128.10.30 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.10.60 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.10.60 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.10.60 Value" layout="above" label=""/>
              <display item="CV128.10.60 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.10.70 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.10.70 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.10.70 Value" layout="above" label=""/>
              <display item="CV128.10.70 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
      </column>
      <column>
        <label label="        "/>
      </column>
      <column>
        <row>
          <column>
            <display item="CV128.11.0 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.11.0 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.11.0 Value" layout="above" label=""/>
              <display item="CV128.11.0 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.11.10 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.11.10 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.11.10 Value" layout="above" label=""/>
              <display item="CV128.11.10 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.11.20 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.11.20 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.11.20 Value" layout="above" label=""/>
              <display item="CV128.11.20 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.11.30 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.11.30 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.11.30 Value" layout="above" label=""/>
              <display item="CV128.11.30 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.11.60 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.11.60 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.11.60 Value" layout="above" label=""/>
              <display item="CV128.11.60 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
        <row>
          <column>
            <display item="CV128.11.70 Sign" format="onradiobutton" label="" layout="left"/>
            <display item="CV128.11.70 Sign" format="offradiobutton" label="" layout="left"/>
          </column>
          <column>
            <row>
              <display item="CV128.11.70 Value" layout="above" label=""/>
              <display item="CV128.11.70 Value" layout="above" format="hslider-percent"/>
            </row>
          </column>
        </row>
        <label label=" "/>
      </column>
    </row>
    <label label=" "/>
    <label label="Sets the relative volumes of the two speakers, adjust overall volume on the Volume tab"/>
    <label label="Please treat the 'Off' in the sliders as '0%' also slider is percent reduction of selected speaker"/>
    <label label="If silder is at 'Off' read as 0% reduction, ie both speakers are 100% of volume setting as set on Volume tab"/>
    <label label="If Speaker 1 selected and silder is at '50%', speaker 1 is half the volume as speaker 2 and speaker 2 is as set on Volume tab"/>
    <label label="If Speaker 2 selected and silder is at '100%', speaker 2 is silent and speaker 1 is as set on Volume tab"/>
  </column>
</pane>
