=== JMRI/jmri-test/xml/DTD/decoder-config.dtd
<!-- Defines XML documenting a DCC decoder as a component, esp. information -->
<!-- on how to program it. -->
<!-- $Id: decoder-config.dtd,v 1.9 2001-11-27 03:26:33 jacobsen Exp $ -->

<!ELEMENT decoder-config (decoder*)>
<!ATTLIST decoder-config xmlns:decoder CDATA "">

<!ELEMENT decoder (id, programming, variables)>


<!-- The id section identifies the decoder -->

<!ELEMENT id EMPTY>
<!ATTLIST id family     CDATA #REQUIRED>  <!--family name used for identification -->
<!ATTLIST id mfg       CDATA #REQUIRED>  <!-- mfg name used for identification   -->
<!ATTLIST id type      ( stationary | locomotive ) "locomotive">
<!ATTLIST id versionID CDATA "XX" >      <!-- CV07 value, default XX means any   -->
<!ATTLIST id mfgID     CDATA #REQUIRED>  <!-- CV08 value, XX means any           -->
<!ATTLIST id defnVersion CDATA #REQUIRED> <!-- version of the XML defining the decoder -->
<!ATTLIST id comment   CDATA #IMPLIED>


<!-- The programming section describes the decoders programming capabilities -->

<!ELEMENT programming EMPTY>
<!ATTLIST programming direct   ( no | yes | bitOnly | byteOnly ) "no" >  <!-- direct mode support -->
<!ATTLIST programming paged    ( no | yes ) "no" >               <!-- paged mode support -->
<!ATTLIST programming register ( no | yes ) "no" >               <!-- register mode support -->
<!ATTLIST programming ops      ( no | yes ) "no" >               <!-- operation mode support -->
<!ATTLIST programming comment   CDATA #IMPLIED>


<!-- The variables section defines the list of identified variables -->
<!-- and how they are encoded into CVs -->

<!ELEMENT variables (variable*)>

<!ELEMENT variable  (enumVal | binaryVal | 
                             decVal | hexVal | 
                             speedTableVal | longAddressVal ) >
<!ATTLIST variable name CDATA #REQUIRED>  <!-- Name used for identification -->
<!ATTLIST variable CV CDATA #REQUIRED>    <!-- CV number containing value -->
<!ATTLIST variable mask CDATA "VVVVVVVV">    <!-- mask of bits within CV -->
                                           <!-- mask is up to 16 characters long, each -->
                                           <!-- representing one bit in the result -->
                                           <!-- valid chars: -->
                                           <!--     X   not used     -->
                                           <!--     V   used bits    -->
<!ATTLIST variable readOnly  (yes | no) "no" >
<!ATTLIST variable comment   CDATA #IMPLIED>
<!ATTLIST variable stdName CDATA #IMPLIED>  <!-- "standard name" for this function if different -->
<!ATTLIST variable minFn CDATA #IMPLIED>  <!-- min number of fns in decoder for this to be valid -->
<!ATTLIST variable inOptions CDATA #IMPLIED>  <!-- variable present if any of the options are present -->

<!-- enumVal, decVal, hexval, speedTableVal, lognAddressVal are constraints on possible values -->

<!ELEMENT decVal EMPTY>
<!ATTLIST decVal min CDATA "0" >    <!-- if decimal/hex, smallest acceptable value -->
<!ATTLIST decVal max CDATA "255" >  <!-- if decimal/hex, largest acceptable value -->
<!ATTLIST decVal default CDATA #IMPLIED>

<!ELEMENT hexVal EMPTY>
<!ATTLIST hexVal min CDATA "0" >    <!-- if decimal/hex, smallest acceptable value -->
<!ATTLIST hexVal max CDATA "ff" >  <!-- if decimal/hex, largest acceptable value -->
<!ATTLIST hexVal default CDATA #IMPLIED>

<!ELEMENT enumVal (enumChoice*) >
<!ATTLIST enumVal default CDATA #IMPLIED>
<!ATTLIST enumVal comment CDATA #IMPLIED>

<!ELEMENT enumChoice EMPTY>
<!ATTLIST enumChoice choice CDATA #REQUIRED >
<!ATTLIST enumChoice comment CDATA #IMPLIED >
<!ATTLIST enumChoice value CDATA "" >

<!ELEMENT speedTableVal (speedTableEntry*) >
<!ATTLIST speedTableVal entries CDATA "28">        <!-- number of entries/CVs in table -->
<!ATTLIST speedTableVal comment CDATA #IMPLIED>

<!ELEMENT speedTableEntry EMPTY>
<!ATTLIST speedTableEntry step  CDATA #REQUIRED >
<!ATTLIST speedTableEntry value CDATA #REQUIRED >

<!ELEMENT longAddressVal EMPTY >
<!ATTLIST speedTableVal comment CDATA #IMPLIED>

=== JMRI/jmri-test/xml/decoders/Lenz_LE077XF.xml
<?xml version="1.0"?>
<!DOCTYPE decoder-config SYSTEM "decoder-config.dtd">
<!-- $Id: Lenz_LE077XF.xml,v 1.4 2002-01-13 03:36:57 jacobsen Exp $ -->
<decoder-config>
		<version author="Joe Ellis filker@mindspring.com"
			version="2" lastUpdated="20020112" />
			<!-- Updated to new names by jake@physics.berkeley.edu -->

<decoder>
	<id family="Lenz" mfg="Lenz" mfgID="" defnVersion=""
				comment="Lenz LE077XF"></id>

	<programming direct="byteOnly" paged="yes"
	                     register="yes" ops="yes"></programming>

	<variables>

		<variable label="Short Address" CV="1"
		          default="03" comment="Range 1-127">
			<decVal min="1" max="127"/>
			</variable>

		<variable label="Kick Start" CV="2"
				comment="Range 0-31">
			<decVal></decVal>
			</variable>

		<variable label="Accel" CV="3"
				comment="Range 0-31">
			<decVal max="31"/>
			</variable>

		<variable label="Decel" CV="4"
				comment="Range 0-31">
			<decVal max="31"/>
			</variable>

<!-- deleted max and mid voltage-->

		<variable label="Version ID" CV="7" readOnly="yes"
				item="Decoder Version" >
			<decVal/>
			</variable>

		<variable label="Manufacturer ID" CV="8" readOnly="yes"
				item="Manufacturer">
			<decVal default="99"/>
			</variable>


		<variable label="Manufacturer ID - Reset" CV="8">
			<decVal default="99"/>
			</variable>

<!-- Deleted all CV 13 references-->

		<variable label="Long Address" CV="17" item="Extended Address"
		        comment="4 digit address (Range 0001-9999)">
			<longAddressVal/>
			</variable>

		<variable label="Advanced Consist Address" CV="19"
				item="Consist Address"
				comment="Allows permanent storage of consist address. Range 0-255">
			<decVal/>
			</variable>

		<variable label="Acceleration Trim (range 0-255)" CV="23"
				item="Consist Acceleration Adjustment"
		        comment="Additional Acceleration rate info for fine-tuning. (Range 0-255)">
			<decVal default="255" min="0" max="255"/>
			</variable>

		<variable label="Deceleration Trim (range 0-255)" CV="24"
				item="Consist Deceleration Adjustment"
		        comment="Additional Deceleration (braking) rate info for fine-tuning. (Range 0-255)">
			<decVal default="255" min="0" max="255"/>
			</variable>

		<variable label="Normal direction of motion" CV="29"
				mask="XXXXXXXV"
		        item="Locomotive Direction">
			<enumVal>
				<enumChoice choice="Forward"/>
				<enumChoice choice="Reverse"/>
				</enumVal>
			</variable>

		<variable label="Speed Steps" CV="29" mask="XXXXXXVX"
				item="Speed Step Mode" default="1">
			<enumVal>
				<enumChoice choice="14"/>
				<enumChoice choice="28/128 (recommended)"/>
				</enumVal>
			</variable>

		<variable label="Analog conversion mode" CV="29"
				mask="XXXXXVXX" default="1"
				item="Analog (DC) Operation">
			<enumVal>
				<enumChoice choice="Off"/>
				<enumChoice choice="On"/>
				</enumVal>
			</variable>

		<variable label="Use Speed Table" CV="29" mask="XXXVXXXX"
				item="Speed Table Definition">
			<enumVal>
				<enumChoice choice="Use Vstart, Vmid, Vhigh"/>
				<enumChoice choice="Use Table"/>
				</enumVal>
			</variable>

		<variable label="Addressing Mode" CV="29" mask="XXVXXXXX"
				item="Address Format">
			<enumVal>
				<enumChoice choice="2 digit addressing"/>
				<enumChoice choice="4 digit addressing"/>
				</enumVal>
			</variable>

	<variable label="Accel/Decel Trim" CV="50"
				mask="XXXXXXXV"
	          	comment="Governs how loco acts in DC track block">
  			<enumVal>
				<enumChoice choice="Accel/Decel trim OFF"/>
				<enumChoice choice="Accel/Decel trim ON"/>
				</enumVal>
			</variable>


	<variable label="Brake Momentum on DC" CV="50" 
				item="DC Brake Momentum" mask="XXXXXVXX"
	          	comment="Governs how loco acts in DC track block">
			<enumVal>
				<enumChoice choice="Loco runs under DC analog voltage control"/>
				<enumChoice choice="Loco brakes to a stop using momentum set in CV4"/>
		        </enumVal>
			</variable>

	<variable label="Directional Headlights" CV="51"
	          	comment="Controls how headlights respond to a change of direction"
               	mask="XXXXXXXV">
		     <enumVal>
		         <enumChoice choice="Headlights are directional and operate automatically"/>
		         <enumChoice choice="Headlights are independantly controlled (F0-Front, F1-Rear)"/>
		         </enumVal>
			</variable>

	<variable label="Function Dimming" CV="51"
				item="Global lighting option 1"
	         	comment="Controls how headlights dim (CV 52 controls amount)"
              	mask="XXXXXXVX">
		     <enumVal>
		         <enumChoice choice="Dimming Disabled"/>
		         <enumChoice choice="F0 dims headlight"/>
		         </enumVal>
			</variable>

	<variable label="Rule 17 Headlights - Front" CV="51" 
				item="Global lighting option 2"
	          	comment="Controls how front headlights dim"
               	mask="XXXXXVXX">
		     <enumVal>
		         <enumChoice choice="Front Headlight dimming OFF"/>
		         <enumChoice choice="Front Headlight dimming ON (F4 dims F0)"/>
		         </enumVal>
			</variable>

	<variable label="Rule 17 Headlights - Rear" CV="51" 
				item="Global lighting option 3"
	         	comment="Controls how rear headlights dim"
               	mask="XXXXVXXX">
			<enumVal>
		         <enumChoice choice="Rear Headlight dimming OFF"/>
		         <enumChoice choice="Rear Headlight dimming ON (F4 dims F1)"/>
		         </enumVal>
			</variable>

	<variable label="Dimmer Control (range 0-255)" CV="52"
				item="Global lighting option 4"
	          	comment="Controls how much headlights dim (0-dark to 255-max bright)">
			<decVal min="0" max="255"/>
			</variable>


		<variable label="User Private ID #1" CV="105"
					item="User Id #1">
			<decVal/>
			</variable>

		<variable label="User Private ID #2" CV="106"
					item="User Id #2">
			<decVal/>
			</variable>

		<variable label="Speed Table" CV="67">
			<speedTableVal/>
			</variable>


	<!-- Define the fixed Function-Output mapping -->
	<constant label="FL(f) controls output 1" minOut="1" default="1" /> 
	<constant label="FL(r) controls output 2" minOut="2" default="1" /> 
	<constant label="F1 controls output 3" minOut="3" minFn="1" default="1" /> 
	<constant label="F2 controls output 4" minOut="4" minFn="2" default="1" /> 
	<constant label="F3 controls output 5" minOut="5" minFn="3" default="1" /> 
	<constant label="F4 controls output 6" minOut="6" minFn="4" default="1" /> 
	<constant label="F5 controls output 7" minOut="7" minFn="5" default="1" /> 
	<constant label="F6 controls output 8" minOut="8" minFn="6" default="1" /> 
	<constant label="F7 controls output 9" minOut="9" minFn="7" default="1" /> 
	<constant label="F8 controls output 10" minOut="10" minFn="8" default="1" /> 

	</variables>

</decoder>

<pane name="Lenz">
	<column>
		<display item="Manufacturer ID - Reset" 
			label="To restore ALL CVs to factory default values, set Manufacturer ID to 33"
			layout="left"/>
		<label label="" />
		<display item="Accel/Decel Trim" />
	</column>
</pane>

</decoder-config>
