=== JMRI/jmri-test/xml/DTD/programmer-config.dtd
<!-- Defines XML documenting a CV programmer format -->

<!ELEMENT programmer:programmer-config (programmer:programmer*)>
<!ATTLIST programmer:programmer-config xmlns:programmer CDATA "">

<!ELEMENT programmer:programmer (programmer:pane*)>


<!-- The pane sections define each tabbed pane of options -->

<!ELEMENT programmer:pane (programmer:column*)>
<!ATTLIST programmer:pane name CDATA #REQUIRED>  <!-- Name used for identification -->

<!-- The column section describes each column in the pane -->

<!ELEMENT programmer:column ((programmer:variable | programmer:separator)*)>

<!-- Insert a separator line -->

<!ELEMENT programmer:separator EMPTY>

<!-- The variable items define each identified variables -->
<!-- in the column and how they are displayed -->

<!ELEMENT programmer:variable EMPTY >
<!ATTLIST programmer:variable name CDATA #REQUIRED>  <!-- Name used for identification -->
<!ATTLIST programmer:variable label CDATA "">  <!-- optional, default is from variable -->
<!ATTLIST programmer:variable popup CDATA "">  <!-- optional, default is from variable -->
<!ATTLIST programmer:variable format  (default | radio ) "default" >

=== JMRI/jmri-test/xml/programmers/MultiPane.xml
<?xml version="1.0"?>
<!DOCTYPE programmer-config SYSTEM "programmer-config.dtd">
<programmer-config xmlns:programmer="http://jmri.sourceforge.net/xml/programmer">
<!-- $Id: MultiPane.xml,v 1.11 2001-12-06 16:17:06 jacobsen Exp $ -->
<programmer>

	<pane name="Basic">
		<column>
			<variable name="Short Address"/>
			<variable name="Long Address"/>
			<variable name="Address Format"/>

			<dccaddress/>
			
			<variable name="Locomotive Direction" format="radiobuttons" layout="left"/>
			<variable name="User Id #1"/>
			<variable name="User Id #2"/>
			<variable name="Speed Step Mode" layout="above"/>
			<variable name="Power Source Conversion" format="radiobuttons" layout="left"/>
			<variable name="Analog (DC) Operation" format="checkbox"/>
		</column>
	</pane>
	
	<pane name="Motor">
		<column>
			<variable name="Kick Start"/>
			<variable name="Accel"/>
			<variable name="Decel"/>
			<label label=" "/>
			<variable name="Total PWM Period"/>
		</column>
		<column>
			<variable name="EMF Static Config"/>  <!-- Not an NMRA S&RP term -->
			<variable name="EMF Dynamic Config"/>  <!-- Not an NMRA S&RP term -->
			<variable name="EMF Droop Config"/>  <!-- Not an NMRA S&RP term -->
			<variable name="EMF Feedback Cutout"/>
		</column>
	</pane>
	
	<pane name="Speed Control">
		<column>
			<variable name="Speed Table Definition" format="offradiobutton" layout="above"/>
			<variable name="Vstart"/>
			<variable name="Vmid"/>
			<variable name="Vhigh"/>
			<variable name="Forward Trim"/>
			<variable name="Reverse Trim"/>
		</column>
		<column>
			<variable name="Speed Table Definition" format="onradiobutton" layout="above"/>
			<variable name="Speed Table"/>
		</column>
	</pane>

	<pane name="Function Map">
		<column>
			<fnmapping/>
		</column>
	</pane>

	<pane name="Light FX">
		<column>
			<variable name="Function F0F effect generated"/>
			<variable name="Function F0F behaviour"/>
			<separator/>
			<variable name="Function F0R effect generated"/>
			<variable name="Function F0R behaviour"/>
			<separator/>
			<variable name="Function 1 effect generated"/>
			<variable name="Function 1 behaviour"/>
			<separator/>
			<variable name="Function 2 effect generated"/>
			<variable name="Function 2 behaviour"/>
			<separator/>
			<variable name="Function 3 effect generated"/>
			<variable name="Function 3 behaviour"/>
			<separator/>
			<variable name="Function 4 effect generated"/>
			<variable name="Function 4 behaviour"/>
			<separator/>
			<variable name="Function 5 effect generated"/>
			<variable name="Function 5 behaviour"/>
			<separator/>
			<variable name="Function 6 effect generated"/>
			<variable name="Function 6 behaviour"/>
			<separator/>
			<variable name="Function 7 effect generated"/>
			<variable name="Function 7 behaviour"/>
			<separator/>
			<variable name="Function 8 effect generated"/>
			<variable name="Function 8 behaviour"/>
			<separator/>
		</column>
		<column>
			<variable name="Analog Mode Function Status - F1" format="checkbox"/>			
			<variable name="Analog Mode Function Status - F2" format="checkbox"/>			
			<variable name="Analog Mode Function Status - F3" format="checkbox"/>			
			<variable name="Analog Mode Function Status - F4" format="checkbox"/>			
			<variable name="Analog Mode Function Status - F5" format="checkbox"/>			
			<variable name="Analog Mode Function Status - F6" format="checkbox"/>			
			<variable name="Analog Mode Function Status - F7" format="checkbox"/>			
			<variable name="Analog Mode Function Status - F8" format="checkbox"/>			
		</column>
	</pane>

	<pane name="Consist">
		<column>
			<variable name="Consist Address" />
			<variable name="Consist Acceleration Adjustment" />
			<variable name="Consist Acceleration Adjustment Sign" />
			<variable name="Consist Deceleration Adjustment" />
			<variable name="Consist Deceleration Adjustment Sign" />
			<separator/>
			<label label="Will decoder respond to function requests at consist address?"/>
			<variable name="Consist Address Active For F1"  format="checkbox"/>
			<variable name="Consist Address Active For F2"  format="checkbox"/>
			<variable name="Consist Address Active For F3"  format="checkbox"/>
			<variable name="Consist Address Active For F4"  format="checkbox"/>
			<variable name="Consist Address Active For F5"  format="checkbox"/>
			<variable name="Consist Address Active For F6"  format="checkbox"/>
			<variable name="Consist Address Active For F7"  format="checkbox"/>
			<variable name="Consist Address Active For F8"  format="checkbox"/>
			<variable name="Consist Address Active For FL in Forward"  format="checkbox"/>
			<variable name="Consist Address Active For FL in Reverse"  format="checkbox"/>
		</column>
	</pane>
	
	<pane name="Communications">
		<column>
			<variable name="Advanced Ack" />
		</column>
	</pane>

	<pane name="Sound">
		<column>
		</column>
	</pane>

	<pane name="Sound Levels">
		<column>
		</column>
	</pane>

	<pane name="CVs">
		<column>
			<cvtable/>
		</column>
	</pane>

</programmer>
</programmer-config>
