=== JMRI/jmri-test/jake1/xml/schema/programmer.xsd
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>

<!-- Schema for JMRI programmer definitions       -->

<!-- $Id$ -->

<!-- This schema is part of JMRI. Copyright 2009, 2010.                     -->
<!--                                                                        -->
<!-- JMRI is free software; you can redistribute it and/or modify it under  -->
<!-- the terms of version 2 of the GNU General Public License as published  -->
<!-- by the Free Software Foundation. See the "COPYING" file for a copy     -->
<!-- of this license.                                                       -->
<!--                                                                        -->
<!-- JMRI is distributed in the hope that it will be useful, but WITHOUT    -->
<!-- ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or  -->
<!-- FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License  -->
<!-- for more details.                                                      -->


    <!-- need variable -->
    
    <!-- not yet in proper Venetian blind form -->
    <!-- needs to share the pane type with programmer definition -->
    
    <!-- need documentation, etc -->

    <!-- need attribute restrictions -->
    <!-- need attribute defaults -->
    
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:docbook="http://docbook.org/ns/docbook"
           xmlns:jmri="http://jmri.org/xml/schema/JMRIschema"
           xsi:schemaLocation="
                http://jmri.org/xml/schema/JMRIschema http://jmri.org/xml/schema/JMRIschema.xsd
                http://docbook.org/ns/docbook http://jmri.org/xml/schema/docbook/DocBook.xsd
            "
        >

    <xs:include schemaLocation="http://jmri.org/xml/schema/types/general.xsd"/>
    <xs:import namespace='http://docbook.org/ns/docbook' schemaLocation='http://jmri.org/xml/schema/docbook/DocBook.xsd'/>

<xs:annotation>
    <xs:documentation>
      Defines the JMRI programmer definition files.
    </xs:documentation>
    <xs:appinfo>
        <jmri:usingclass configurexml="false">jmri.jmrit.decoderdefn.DecoderFile</jmri:usingclass>
        <jmri:usingclass configurexml="false">jmri.jmrit.symbolicprog.VariableTableModel</jmri:usingclass>
    </xs:appinfo>
</xs:annotation>

  <xs:complexType name="VersionType">
      <xs:attribute name="author" type="xs:string" />
      <xs:attribute name="version" type="xs:string" />
      <xs:attribute name="lastUpdated" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ProgrammerType">
    <xs:sequence>

      <xs:element name="pane" type="PaneType" minOccurs="0" maxOccurs="unbounded" />

    </xs:sequence>
    <xs:attribute name="decoderFilePanes"  type="yesNoType" default="yes"/>
    <xs:attribute name="showEmptyPanes"  type="yesNoDefaultType" default="default"/>
    <xs:attribute name="showFnLanelPane"  type="yesNoType" default="no"/>
    <xs:attribute name="showRosterPane"  type="yesNoType" default="no"/>
    <xs:attribute name="showRosterMediaPane"  type="yesNoType" default="no"/>
  </xs:complexType>

  <xs:element name="programmer-config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" type="VersionType" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="programmer" type="ProgrammerType" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:complexType name="PaneType">
    <xs:sequence>
      <xs:element name="name" minOccurs="0" maxOccurs="unbounded" />
      <xs:choice>
        <xs:element name="row" type="PaneRowType" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="column" type="PaneColumnType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="nameFmt" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="PaneRowType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="column" type="PaneColumnType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="label" type="LabelType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="display" type="DisplayType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="separator" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="dccaddress" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="fnmapping" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="cvtable" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="indxcvtable" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PaneColumnType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="row" type="PaneRowType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="label" type="LabelType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="display" type="DisplayType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="separator" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="dccaddress" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="fnmapping" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="cvtable" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="indxcvtable" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LabelType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="label" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation><xs:documentation>Provide internationalized label text</xs:documentation></xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="label" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="DisplayType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="label" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation><xs:documentation>Provide internationalized label text</xs:documentation></xs:annotation>
      </xs:element>
      <xs:element name="tooltip" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation><xs:documentation>Provide internationalized tooltip text</xs:documentation></xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="item" type="xs:string"/>
    <xs:attribute name="label" type="xs:string"/>
    <xs:attribute name="format">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="default" />
                <xs:enumeration value="vslider" />
                <xs:enumeration value="hslider" />
                <xs:enumeration value="hslider-percent" />
                <xs:enumeration value="radiobuttons" />
                <xs:enumeration value="checkbox" />
                <xs:enumeration value="onradiobutton" />
                <xs:enumeration value="offradiobutton" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="layout" type="xs:string"/>
    <xs:attribute name="tooltip" type="xs:string"/>
  </xs:complexType>

  <xs:element name="pane" type="PaneType">
    <xs:annotation><xs:documentation>
      Can appear as top-level element in xml/programmer/parts files.
    </xs:documentation></xs:annotation>
  </xs:element>

</xs:schema>

=== JMRI/jmri-test/xml/programmers/parts/BasicPane.xml
<?xml version="1.0" encoding="utf-8"?>
<pane xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://jmri.org/xml/schema/programmer.xsd">
  <name>Basic</name>
  <name xml:lang="ca">Bàsic</name>
  <name xml:lang="it">Basic</name>
  <name xml:lang="de">Basic</name>
  <column>
    <dccaddress/>
    <label>
      <text> </text>
    </label>
    <display item="Short Address" tooltip="Sets the primary (short) address">
      <tooltip xml:lang="it">Indirizzo Corto"</tooltip>
      <tooltip xml:lang="ca">Establir adreÁa prim‡ria (short)</tooltip>
      <tooltip xml:lang="de">Sets the primary (short) address</tooltip>
    </display>
    <display item="Long Address" tooltip="Sets the extended (long) address">
      <tooltip xml:lang="it">Imposta l'indirizzo esteso</tooltip>
      <tooltip xml:lang="ca">Establir adreÁa llarga</tooltip>
      <tooltip xml:lang="de">Sets the extended (long) address</tooltip>
    </display>
    <display item="Address Format" tooltip="Determines whether loco will use short or long address">
      <tooltip xml:lang="it">Determina se la Loco usa l'indirizzo corto o quello esteso</tooltip>
      <tooltip xml:lang="ca">Determina si es fa servir adreÁa curta o llargaî</tooltip>
      <tooltip xml:lang="de">Determines whether loco will use short or long address</tooltip>
    </display>
    <label>
      <text> </text>
    </label>
    <display item="Locomotive Direction" tooltip="Sets the relative direction of the loco when told to move forward">
      <tooltip xml:lang="it">Imposta la Direzione di movimento della Loco per Comando Avanti</tooltip>
      <tooltip xml:lang="ca">Estableix el sentit de circulaciÛ de la locomotora</tooltip>
      <tooltip xml:lang="de">Sets the relative direction of the loco when told to move forward</tooltip>
    </display>
    <display item="Speed Step Mode" tooltip="Sets the speed step mode for headlight control">
      <tooltip xml:lang="it">Imposta gli Step Velocità di default per Comando Luci</tooltip>
      <tooltip xml:lang="ca">Estableix els passos de velocitat per al control de llums</tooltip>
      <tooltip xml:lang="de">Sets the speed step mode for headlight control</tooltip>
    </display>
    <display item="Analog (DC) Operation" tooltip="Determines whether loco can operate on conventional DC current (enables Power Source Conversion)">
      <tooltip xml:lang="it">Determina se la Loco può operare in DC (analogica)</tooltip>
      <tooltip xml:lang="ca">Estableix que la locomotora pot circular en analÚgic [CC] (ConversiÛ de Font de potËncia)</tooltip>
      <tooltip xml:lang="de">Determines whether loco can operate on conventional DC current (enables Power Source Conversion)</tooltip>
    </display>
  </column>
  <column>
    <label>
      <text> </text>
    </label>
    <label>
      <text> </text>
    </label>
    <display item="User Id #1" tooltip="Sets a custom user ID or number">
      <tooltip xml:lang="it">Imposta un ID Utente o un Codice</tooltip>
      <tooltip xml:lang="ca">1r n˙mero usuari</tooltip>
      <tooltip xml:lang="de">Sets a custom user ID or number</tooltip>
    </display>
    <display item="User Id #2" tooltip="Sets a custom user ID or number">
      <tooltip xml:lang="it">Imposta un ID Utente o un Codice</tooltip>
      <tooltip xml:lang="ca">2n n˙mero usuari</tooltip>
      <tooltip xml:lang="de">Sets a custom user ID or number</tooltip>
    </display>
    <label>
      <text> </text>
    </label>
    <separator/>
    <label>
      <text> </text>
    </label>
    <display item="Manufacturer" tooltip="The manufacturer's ID number (read only)">
      <tooltip xml:lang="it">ID Costruttore (sola lettura)</tooltip>
      <tooltip xml:lang="ca">N˙mero de fabricant (nomÈs lectura)</tooltip>
      <tooltip xml:lang="de">The manufacturer's ID number (read only)</tooltip>
    </display>
    <display item="Decoder Version" tooltip="The decoder version number (read only)">
      <tooltip xml:lang="it">Numero versione del Decoder (sola lettura)</tooltip>
      <tooltip xml:lang="ca">N˙mero de versiÛ del descodificador (nomÈs lectura)</tooltip>
      <tooltip xml:lang="de">The decoder version number (read only)</tooltip>
    </display>
    <display item="Product Number" tooltip="The decoder product number (if used) (read only)">
      <tooltip xml:lang="it">Codice di prodotto del Decoder (se usato) (sola lettura)</tooltip>
      <tooltip xml:lang="ca">La referËncia del descodificador (nomÈs si es fa servir) (nomÈs lectura)</tooltip>
      <tooltip xml:lang="de">The decoder product number (if used) (read only)</tooltip>
    </display>
  </column>
</pane>
